---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Creating a file with content
    copy:
      dest: "/usr/tmp/hello.txt"
      mode: 0755
      content: |
        line 01
        line 02
        line "{{ lookup('amazon.aws.aws_secret', 'fileString') }}"
