---
- hosts: all
  tasks:
  - name: Install requirements
    pip:
      requirements: /my_app/requirements.txt
      virtualenv: /user/home/venvs/myenv
      virtualenv_python: python3.7
  - name: Creating a file with content
    vars:
      ansible_python_interpreter: /usr/bin/python3
    copy:
      dest: "/usr/tmp/hello.txt"
      mode: 0755
      content: |
        line 01
        line 02
        line "{{ lookup('amazon.aws.aws_secret', 'fileString') }}"
...