- hosts: localhost
  tasks:
  - name: install pip
    yum:
      name:
        - python-pip
  - name: Install boto3/core and awscli
    pip:
      name:
        - boto3
        - botocore
        - awscli
      state: present
      executable: pip
      extra_args: --no-cache-dir
  - name: Creating a file with content
    copy:
      dest: "/usr/tmp/hello.txt"
      mode: 0755
      content: |
        line 01
        line 02
        line "{{ lookup('amazon.aws.aws_secret', 'fileString', region='us-west-2') }}"
...